### PR TITLE
Missing agate environment variables in docker-compose.xml

### PR DESCRIPTION
**Pull request by jonathanmasseurca**

### CODE REVIEW

**Comment by ymarcon** [comment]
I don't think it is necessary: Agate is optional for Opal, there is no Agate defined in this docker compose file and using agate-test is misleading.

**Comment by jonathanmasseurca** [comment]
If you need agate and you don’t define the variable, it will get overwrited in file opal-config.properties when the docker start in (start.sh)

**Comment by jonathanmasseurca** [comment]
Maybe a comment saying that if you need agate uncomment the required lines in the docker-compose.xml would help

**Comment by ymarcon** [comment]
I understand your concern with the agate setting but this docker file aims at defining a stand alone opal instance, i.e. without agate: it is expected that no agate variables are defined in this file.

**Pull request closed without merging**
